### PR TITLE
#153009253 Integrate Coveralls code coverage service

### PR DESCRIPTION
**Pull request by codestaintin**
#### What does this PR do?

Intergrate coveralls and code coverage service

#### Description of Task to be completed?

- Install nyc package
- Create a .coveralls.yml file in the project folder
- Obtain repo token from coveralls.io and add to .coveralls.yml file
- Update .gitignore file
- Create a script to run coverage in package.json file

#### How should this be manually tested?
- Clone the repository
- Run `git checkout chore/153009253/integrate-coveralls-code-coverage-service`
- Run `npm test`

#### Any background context you want to provide?

N/A
#### What are the relevant pivotal tracker stories?

- story type: chore
- story id: 153009253
- story title: Integrate Coveralls code coverage service

#### Screenshots (if appropriate)
screen shot 2017-11-22 at 3 07 34 pm

#### Questions:

N/A

### CODE REVIEW

**Comment by damakahindi** [comment]
Please resolve the merge conflicts. The badge doesn't reflect the coverage on coveralls.

**Comment by damakahindi** [comment]
The logging is goe awesome job.

**Review by fuchodeveloper — COMMENTED** [review]
Awesome job. Please check the .gitignore file, it contains a conflict

**Comment by damakahindi** [comment]
Looks good to me.

**Pull request merged**
